# -*- coding: utf-8 -*-
"""Day5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W9J6yJXhDeg37E2kIKseJs4dJKqHrqUJ
"""

#1 eligible to vote
age=int(input("enter age  "))
if age>=18:
    print("eligible to vote")
else:
    print("not eligible")

#2 even or odd
n=int(input("enter a number"))
if(n%2==0):print('even number')
else:
         print('odd number')

#3 string reversing
str="hello"
slicedstr=str[::-1]
print(slicedstr)

#4 +ve number or not
n=int(input("enter a number"))
if(n>0):print("+ve number")
else:
     print("not +ve number")

a=float(input("enter a number "))
b=float(input("enter a number "))
c=float(input("enter a number "))
d=(b*b)-(4*a*c)
r1=(-b+d)/(2*a)
r2=(-b-d)/(2*a)
if(d>0):
        print("roots are real and distinct")
if(d<0):        
        print("roots are imaginary")
if(d==0):
         print("roots are equal")

#6 +ve/-ve/0 using nested if

a=int(input("enter a number "))
if a>0:
       print("number is +ve")
if a<0:
       print("number is -ve")
if a==0:
     print("zero")

#7 print given no

n=int(input("enter number 1 to 5 "))
number=('','one','two','three','four','five')
print(number[n])

#8 vowels or consonant

ch=input("enter a char ")

if(ch=='A' or ch=='a' or ch=='E' or ch =='e' or ch=='I'
 or ch=='i' or ch=='O' or ch=='o' or ch=='U' or ch=='u'): print("vowels")
else:
      print("consonant")

